eyurtsev/kor

- .github/workflows/test.yml
> Add unit testing to CI

- README.md
> Add test badge to README.md

- README.md
> Update README.md with more info

- README.md
> Add TLDR example to README.md

- docs/source/index.rst
> Add TLDR to sphinx docs

- tests/test_examples.py
- tests/test_type_descriptors.py
> Add more tests

- kor/type_descriptors.py
- tests/test_type_descriptors.py
Add tests for type descriptors
> Add tets for type descriptors

- docs/source/conf.py
- kor/__init__.py
- kor/examples.py
- kor/experimental/blocks.py
- kor/extraction.py
- kor/llms/openai.py
- kor/nodes.py
- kor/parsing.py
- kor/prompts.py
- poetry.lock
- pyproject.toml
- tests/test_type_descriptors.py
- tests/test_visitors.py
Add poe the poet
Set up linting and testing
> Set up linting

- .github/workflows/test.yml
- kor/examples.py
- kor/extraction.py
- kor/nodes.py
- kor/parsing.py
- kor/prompts.py
- pyproject.toml
Use poe to run unit tests on CI
> Use poe to run tests on CI

- docs/source/conf.py
- kor/examples.py
- kor/extraction.py
- kor/llms/openai.py
- kor/llms/typedefs.py
- kor/nodes.py
- kor/parsing.py
- kor/prompts.py
- kor/type_descriptors.py
- poetry.lock
- pyproject.toml
- tests/test_nodes.py
> Re-add mypy

- kor/examples.py
- kor/extraction.py
- kor/llms/openai.py
- kor/nodes.py
- kor/parsing.py
- kor/prompts.py
- poetry.lock
- pyproject.toml
- tests/test_examples.py
- tests/test_nodes.py
- tests/test_parsing.py
- tests/test_public_interface.py
- tests/test_type_descriptors.py
- tests/test_visitors.py
> Swap to Ruff for linting

- README.md
Update README with python compatibility
> Update README with python compatibility

- poetry.lock
- pyproject.toml
Remove autoflake
Rename autoformat to fix (faster to type)
> Poe tasks update

- kor/examples.py
- kor/nodes.py
- kor/prompts.py
- pyproject.toml
This PR is used to test the release workflow. So it won't actually be released
until the release workflow is set up properly.
> Ready for v0.3.0 release

- .github/workflows/documentation.yaml
> Change documentation build trigger

- .github/workflows/documentation.yaml
Temporarily change doc publish trigger
> Temporarily change doc publish condition

- docs/source/apis.ipynb
- docs/source/objects.ipynb
- docs/source/prompt_examples.ipynb
- docs/source/tutorial.ipynb
- kor/nodes.py
- kor/prompts.py
- pyproject.toml
Update docs to use langchain integration.
> Update docs to use langchain llm

- .github/workflows/release.yml
> Release v0.3.0

- .github/workflows/release.yml
> Attempt release again

- README.md
- docs/source/index.rst
Update more docs with langchain integration.
> Update more docs with langchain integration

- .github/workflows/release.yml
> Fix release yml one more time

- kor/encoders/csv_data.py
- kor/encoders/typedefs.py
- kor/examples.py
- kor/nodes.py
- kor/prompts.py
- kor/type_descriptors.py
- tests/test_encoders/test_encoders.py
- tests/test_nodes.py
- tests/test_type_descriptors.py
- tests/test_visitors.py
> Rename AbstractNodeInput to AbstractSchemaNode

- kor/encoders/csv_data.py
- kor/encoders/json_data.py
- kor/nodes.py
- tests/test_chain.py
- tests/test_extraction.py
* Add test coverage
* Fix JSON decoder to not crash on invalid JSON decoding
* CSVEncoder to raise NotImplementedError
> Add test coverage and fix json decoder

- kor/__init__.py
- kor/type_descriptors.py
- tests/test_public_interface.py
- tests/test_type_descriptors.py
Shorter names are better names
> Rename typescript descriptors

- docs/source/nested_objects.ipynb
Add missing documentation about nested objects
> Add missing documentation about nested objects

- kor/__init__.py
- kor/nodes.py
- kor/type_descriptors.py
- tests/test_extraction.py
- tests/test_public_interface.py
- tests/test_type_descriptors.py
- tests/test_visitors.py
Expose selection and option nodes.
> Expose Selection and Option nodes

- kor/adapters.py
- tests/test_adapters.py
- tests/test_adpaters.py
This adds minimal handling and safeguards for Union type when working with
pydantic models.
> Minimal handling of union types for pydantic

- poetry.lock
- pyproject.toml
> Update langchain reqs

- pyproject.toml
> Release version 0.5.0

- kor/encoders/__init__.py
- kor/encoders/encode.py
- kor/encoders/parser.py
- kor/extraction.py
- kor/prompts.py
- tests/test_encoders/test_encoders.py
- tests/test_extraction.py
This PR adds input formatting. This helps to improve extraction significantly
when the input is multiparagraph likely as it helps the LLM interpret correctly
the start and end of the text.
> Add input formatting

- kor/encoders/encode.py
- kor/extraction.py
- tests/test_encoders/test_encoders.py
- tests/test_extraction.py
Update options for input encoding
> Update options for input encoding

- kor/encoders/json_data.py
* Add documentation to the JSON encoder
* Fix format instructions to be updated depending on whether tags are used or not
> Add docs to JSON encoder

- kor/__init__.py
- kor/version.py
- tests/test_public_interface.py
Add __version__ to kor public interface
> Add __version__

- pyproject.toml
This is a version 0.5.1 release. See release notes.
> Version 0.5.1

- docs/source/api.rst
- kor/encoders/__init__.py
- kor/encoders/typedefs.py
> Improve encoders docs

- kor/examples.py
- kor/nodes.py
- kor/type_descriptors.py
- tests/test_nodes.py
- tests/test_visitors.py
Allow passing args and kwargs down call chain
> Allow passing arugments down call chain in visitors

- .github/workflows/doc_publish.yaml
- .github/workflows/doc_test.yaml
- .github/workflows/documentation.yaml
Update documentation release workflow
> update documentation workflow

- kor/prompts.py
- kor/type_descriptors.py
- tests/test_nodes.py
- tests/test_type_descriptors.py
- tests/test_visitors.py
Make type-descriptors immutable
> Make type-descriptors immutable

- docs/source/type_descriptors.ipynb
Add documentation for type descriptors
> Add type descriptors documentation

- pyproject.toml
> Version 0.6.0 release

- docs/source/index.rst
Add type-description documentation to the documentation index.
> Add type-description documentation to the documentation index

- docs/source/tutorial.ipynb
> Fix a typo in the docs

- pyproject.toml
Release 0.6.1. See release notes for more details.
> Release v0.6.1

- kor/__init__.py
- kor/encoders/typedefs.py
- kor/extraction/__init__.py
- kor/extraction/api.py
- kor/extraction/extraction.py
- kor/extraction/parser.py
- kor/extraction/typedefs.py
- kor/prompts.py
- poetry.lock
- tests/extraction/test_extraction_from_documents.py
- tests/extraction/test_extraction_with_chain.py
- tests/test_public_interface.py
- tests/utils.py
This PR adds a simple extraction workflow. 
Makes it easier to apply concurrently poroces a set of documents
using a given chain and collect the results.
> Add simple extraction workflow

- pyproject.toml
Release 0.8.0 see release notes.
> Release v0.8.0

- pyproject.toml
> Release v 0.8.1

- tests/test_nodes.py
Add a few tests to verify that instantiation does not lead to unexpected auto-coercion.
> Add node instantiation tests

- pyproject.toml
> Release 0.9.0

- pyproject.toml
> Version 0.9.1

- kor/encoders/json_data.py
- tests/extraction/test_extraction_with_chain.py
- tests/test_encoders/test_encoders.py
- tests/test_encoders/test_json.py
Allow encoding non ascii characters in JSON.
> Fix to allow encoding non ascii in JSON

- kor/encoders/json_data.py
* Update default for ensure_ascii in JSON encoder
* Update doc-strings
> Set default of JSON encoder to ensure_ascii = False

- pyproject.toml
Release 0.9.2 See release notes
> Release 0.9.2

- docs/source/index.rst
- docs/source/prompt.ipynb
Add customize prompt instructions
> Customize prompt instructions

- docs/source/validation.ipynb
> Rename validation to validation with pydantic

- docs/source/guidelines.ipynb
- docs/source/index.rst
> Add guidelines

- README.md
Highlight pydantic in README.md
> Update README.md to highlight pydantic

- pyproject.toml
> Version 0.10.0

- docs/source/document_extraction.ipynb
tiniest PR record attempt, jk, great project ;)
> fix(docs): typo

- docs/source/apis.ipynb
> Fix typo in apis.ipynb

- kor/nodes.py
Minor change to avoid shadowing type and to pop the $type from the dict
> Minor refactor of internal variable names

- pyproject.toml
> Release v0.11.0

- pyproject.toml
> Release v 0.12.0

- pyproject.toml
* Expand flag to full name
* Add missing __init__ file
> Add __init__ and update pyproject pytest flag

- pyproject.toml
> Release 0.13.0

- docs/source/apis.ipynb
- docs/source/nested_objects.ipynb
- docs/source/objects.ipynb
- docs/source/schema_serialization.ipynb
- docs/source/tutorial.ipynb
- docs/source/untyped_objects.ipynb
- docs/source/validation.ipynb
> Update docs to use run

- README.md
> Update README for pydantic v2

- poetry.lock
- pyproject.toml
> Update poetry lock file

- .github/workflows/release.yml
Use main branch nstead of master
> Fix release to use main branch

- pyproject.toml
Upgrade to newer version of langchain
> Version 1.0.1

- poetry.lock
- pyproject.toml
> kor: update constraints for min dependencies

- poetry.lock
- pyproject.toml
Depend only on langchain-core since we no longer use LLMChain
> Depend only on langchain-core

- pyproject.toml
> Release 3.0.0
